### PR TITLE
change to implement props instead of using global state on <MessagesBox />

### PR DESCRIPTION
**Pull request by excessivecoding**

### CODE REVIEW

**Comment by stvnyung** [comment]
As a rule of thumb, always try to pass data locally first (state > props > context > global state).

The more local your component will be by using props and state only the less tide to your application logic it will be. Think for example that you want to reuse the `<MessagesBox />` component in another messenger app, using the global state, you would have to export `useSelectedRoomValue` with it, while if you use props, you will just have to pass the value of the room with the right data.

It seems like a minor thing, but as your application grow, the logic will be bigger everytime and decoupleling component like this will allow for more reusability in the long run.

**Comment by firsi** [comment]
Thanks a lot Steven for the review! 
The main reason I used context is first because : I wanted to practice context.
When building the app, I didn't wanted to pass down props through multiple components. 
For example <MessageList />, to improve reusability, I think what I will have to do is declare my states inside <Content />, pass it down to <MessagesBox /> and finally to <MessageList />.
In this case, some states are going through <MessagesBox /> which doesn't need it. To avoid this problem, I think that is where Redux comes in.
If I'm right, I would like to know what are the best use cases for context ?
Can Redux and Context be used together?

**Comment by excessivecoding** [comment]
I think you are talking about drilling props which is a common case to avoid, but over doing it will result in coupleling you code with your app.

If you find yourself passing some data a lot, like the authenticated user for example, then by all mean use Context or Redux (both are filling the same purpose).
but in the case of those data, it seems like you could avoid it.
Don't be afraid to pass down props for a few levels.

**Comment by firsi** [comment]
Okay!!! I get it now, it's all about finding the happy medium.
I recently read a blog stating that a good developer should know when to break the rules

**Pull request merged**
